; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "KH Switcher"
#define MyAppVersion GetFileVersion("..\bin\Release\KH Switcher.exe")

[Setup]
AppId={{D9C82CF4-82FB-4203-90A1-0E7215BBC5C9}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
OutputBaseFilename={#MyAppName} {#MyAppVersion}
OutputDir=..\bin\Release\{#MyAppVersion}
SetupIconFile=..\Icon.ico
UninstallDisplayIcon={app}\KH Switcher.exe
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}";

[Files]
; Install all files directly to the app root directory
Source: "..\bin\Release\*"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\bin\Release\config.bat"; DestDir: "{app}"; Flags: deleteafterinstall
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Components]
Name: "khMedia"; Description: "KH Switcher Media"; Types: full;
Name: "khZoom"; Description: "KH Switcher Zoom"; Types: full;

[Types]
Name: "full"; Description: "Full installation"
Name: "custom"; Description: "Custom installation"; Flags: iscustom

[Icons]
; Start menu shortcuts
Name: "{autoprograms}\{#MyAppName} Media"; Filename: "{app}\KH Switcher.exe"; Components: khMedia; Parameters: "--client false"; WorkingDir: "{app}";
Name: "{autoprograms}\{#MyAppName} Zoom"; Filename: "{app}\KH Switcher.exe"; Components: khZoom; Parameters: "--client true"; WorkingDir: "{app}";
; Desktop shortcuts
Name: "{autodesktop}\{#MyAppName} Media"; Filename: "{app}\KH Switcher.exe"; Components: khMedia; Parameters: "--client false"; WorkingDir: "{app}"; Tasks: desktopicon;
Name: "{autodesktop}\{#MyAppName} Zoom"; Filename: "{app}\KH Switcher.exe"; Components: khZoom; Parameters: "--client true"; WorkingDir: "{app}"; Tasks: desktopicon;

[Run]
Filename: "{app}\config.bat"; Flags: shellexec runhidden waituntilterminated
